GroundSegment/API/urls.py
'''
Created on 7 jul. 2018

@author: pablo
'''


from django.urls import re_path
from .views import  ParameterViewSet
from .views import SatelliteListView

from django.urls import path
from rest_framework.routers import DefaultRouter
from django.conf.urls import include
from API.views import TlmyVarList,TlmyDictionaryView, UserItemView, CustomAuthToken,\
    UserItemCreateView, GetLastTelemetryTimeStamp, TlmyRawDataView, WSTest
from GroundSegment.models.UserItem import UserItem

"""-----------------API URLS---------------------------"""
"""
http://127.0.0.1:8000/TlmyRawData/
En authorization
username:
password:
{
    "capturedAt": "2022-03-16T00:00:00",
    "pktdatetime": "2022-03-16T00:00:00",
    "source": "RTSatellite",
    "strdata": "RTSatellite",
    "realTime": false,
    "tag": "EMU_RTSatellite"
}
--------------------------------------------------------
http://127.0.0.1:8000/API/api-token-auth/
En Body
username y password
--------------------------------------------------------
http://127.0.0.1:8000/API/SatelliteList
token en headers
"key":"Authorization",
"value":"Token 1111111111111",

http://127.0.0.1:8000/API/TlmyVarDict/TITA
token en headers
"key":"Authorization",
"value":"Token 1111111111111",

http://127.0.0.1:8000/API/TlmyVarList/TITA.CPU_C/647414533287/1647436133287
token en headers
"key":"Authorization",
"value":"Token 1111111111111",
"""
"""----------------------------------------------------"""


router = DefaultRouter()
#Cambie base_name por basename, verificar la razon del problema
try:
    router.register(r'Parameters', ParameterViewSet, basename='Parameter')
except:
    router.register(r'Parameters', ParameterViewSet, base_name='Parameter')
    
#urlpatterns = router.urls

urlpatterns = [
    #Comprobado que es usada por openmct para pedir lista de satelites
    re_path(r'^SatelliteList', SatelliteListView.as_view() , name='SatelliteListView'),
    re_path(r'^', include(router.urls)),

    
    #Comprobado que es usada por el openmct para pedir los valores de las variables de telemetri
    path('TlmyVarList/<str:sat_tlmyId>/<str:afrom>/<str:ato>', TlmyVarList.as_view()),
    #Misma url sin desde hasta
    path('TlmyVarList/<str:sat_tlmyId>/', TlmyVarList.as_view()),
    
    #Comprobado que es usada por el openmct para pedir la lista de tipos de variable de telemetria
    path('TlmyVarDict/<str:satellite>', TlmyDictionaryView.as_view()),
    path('UserItems', UserItemView.as_view()),
    path('UserItems/Create', UserItemCreateView.as_view()),
    path('api-token-auth/', CustomAuthToken.as_view()),
    
    #http://127.0.0.1:8000/API/wstest/
    path('wstest/', WSTest.as_view()),
   
    #http://localhost:8000/API/TlmyVarDict/FS2017
    
    
    #Existe raw data para esta fecha y satelite?
    path('TlmyRawData/<str:satellite>/<str:adatetime>', TlmyRawDataView.as_view()),
    
    
    #http://localhost:8000/API/GetLastTelemetryTimeStamp/TITA
    path('GetLastTelemetryTimeStamp/<str:satellite>', GetLastTelemetryTimeStamp.as_view()),
    
    
    
    
    
    #Open MCT: http://localhost:8080/history/fs2017.BattV?start=1536153300189&end=1536154200189
    
    #url(r'^TlmyVarTypeList/(<int:satellite_id>)/(<int:tlmyVarType_id>)/$', TlmyVarTypeListView.as_view() , name='TlmyVarTypeListView'),
]

GroundSegment/GroundSegment/urls.py
from django.urls import include, re_path
from django.contrib import admin
from API.views import TlmyRawDataList

from django.conf.urls.static import static
from django.conf import settings
from rest_framework.routers import SimpleRouter
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from Telemetry.models.TlmyVarType import TlmyVarType
#from aptsources.distinfo import Template
from Telemetry.models.TlmyVarType import TlmyVarType
from Telemetry import urls



import GroundSegment
#from DistUpgrade.DistUpgradeViewGtk3 import view
from django.views.generic import TemplateView
from GroundSegment.settings import MAPBOX_KEY
import Telemetry
#import debug_toolbar


# Text to put at the end of each page's <title>.
admin.site.site_title = 'MDIAE Ground Segment'

# Text to put in each page's <h1>.
admin.site.site_header = 'MDIAE Ground Segment'
  

# Text to put at the top of the admin index page.
admin.site.index_title = 'Control Panel'

router = SimpleRouter()

#router.register(r'TlmyApi', TlmyRawDataList)


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    
    #url('__debug__/', include(debug_toolbar.urls)),
    re_path(r'^API/', include('API.urls')),
    re_path(r'^telemetry/', include('Telemetry.urls')),
    #re_path(r'^admin/statuscheck/', include('celerybeat_status.urls')),
    re_path(r'^TlmyRawData/$', TlmyRawDataList.as_view(), name='TlmyRawData-APIPost'),
    
    
    ]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    

GroundSegment/GroundSegment/models.py
'''
Created on 16 de ago. de 2016

@author: pabli
'''

GroundSegment/GroundSegment/models/Consts.py
'''
Created on Sep 27, 2016

@author: ubuntumate
'''

class Consts(object):
    '''
    classdocs
    '''
    
    smallString = 64
    mediumString = 128
    bigString = 512


    

    def __init__(self, params):
        '''
        Constructor
        '''
        
    
        

GroundSegment/GroundSegment/models/Country.py
'''
Created on Feb 6, 2017

@author: ubuntumate
'''
from django.db import models
from django.utils.timezone import datetime, now, timedelta, utc


class Country(models.Model):
    code        = models.CharField('Codigo del Pais', max_length=24, unique=True)
    name        = models.CharField('Nombre del Pais', max_length=24, unique=True)
    description = models.CharField('Descripcion', max_length=24, unique=True)
    
    def __str__(self):
        return self.name

GroundSegment/GroundSegment/models/DCPData.py
'''
Created on Jan 25, 2017

@author: ubuntumate
'''

from django.db import models
from django.utils.timezone import datetime, now, timedelta, utc
from GroundSegment.models.DCPPlatform import DCPPlatform
from django.db.models.deletion import PROTECT

class DCPData(models.Model):
 #   sitio       = models.ForeignKey(Sitio,related_name='DCPplatforms')
    dcp_plataform    = models.ForeignKey(DCPPlatform, related_name='dcpdatas', on_delete=PROTECT)
    dataTime         = models.DateTimeField(auto_now_add=True)
    receive_dataTime = models.DateTimeField(auto_now_add=True)
    #snow             = models.FloatField(help_text='Nieve_colchon',default=0.0)
    Precipitation    = models.FloatField(help_text='Precipitacion_Totalizador',default=0.0)
 #   Temperature      = models.FloatField(help_text='Temperatura [C]',default=0.0)

    Humidity         = models.FloatField(help_text='Humedad [%]',default=0.0)
 #   Wind_dir         = models.FloatField(help_text='Direccion del Viento [grados]',default=0.0)
 #   Wind_speed       = models.FloatField(help_text='Velocidad del viento [KPH]',default=0.0)
 #   Bat_volts        = models.FloatField(help_text='Tension de Bateria [volts]',default=0.0)
 #   cm_data          = models.FloatField(help_text='cm ???????',default=0.0)
    Atm_preasure     = models.FloatField(help_text='Presion Atmosferica [%]',default=0.0)
    Temp_max         = models.FloatField(help_text='Temperatura maxima [C]',default=0.0)
    Temp_media         = models.FloatField(help_text='Temperatura media [C]',default=0.0)
    Temp_min         = models.FloatField(help_text='Temperatura minima [C]',default=0.0)
    
    def __str__(self):
        return str(self.Temp_max) 
    

GroundSegment/GroundSegment/models/DCPPlatform.py
'''
Created on Jan 25, 2017

@author: ubuntumate
'''
from django.db import models
from django.utils.timezone import datetime, now, timedelta, utc
from GroundSegment.models.Sitio import Sitio
from django.db.models.deletion import CASCADE


class DCPPlatform(models.Model):
    code        = models.CharField('Codigo de la Plataforma', max_length=24, unique=True)
    
    
    sitio       = models.ForeignKey(Sitio,related_name='dcpplatform', null=True, on_delete=CASCADE)
    type        = models.CharField('Tipo de Plataforma', max_length=24, null=True)
    equip_marca = models.CharField('Marca del Equipo', max_length=24, null=True, default='no conocido')
    equip_model = models.CharField('Modelo del Equipo', max_length=24, null=True, default='no conocido')

    def __str__(self):
        return self.code
    
    def setData(self, datetime,  precipitation, humidity, temp_max, temp_media, temp_min, atm_preasure):
        #TODO, poner datos en tiempo real en esta entidad y utilizar setData para guardar historicos
        #y setear tiempo real, por ahora solo tiempo real
        from GroundSegment.models.DCPData import DCPData
        dspData = DCPData()
        dspData.dcp_plataform   = self
        dspData.dataTime        = datetime
        dspData.receive_dataTime= utc
 #       dspData.snow            = snow
        dspData.Precipitation   = precipitation
 #       dspData.Temperature     = temperature
        dspData.Humidity        = humidity
 #       dspData.Wind_dir        = windDir
 #       dspData.Wind_speed      = windSpeed
 #       dspData.Bat_volts       = batVolt
 #       dspData.cm_data         = cmData
        dspData.Temp_max        = temp_max
        dspData.Temp_media      = temp_media
        dspData.Temp_min        = temp_min
        dspData.Atm_preasure    = atm_preasure
        dspData.save()
        
        return dspData
        
        

GroundSegment/GroundSegment/models/Eclipse.py
'''
Created on Oct 4, 2017

@author: ubuntumate
'''
from datetime import datetime, timedelta
from django.db import models
import ephem
from GroundSegment.models.Satellite import Satellite

from GroundSegment.models.Sitio import Sitio
from GroundSegment.models.PassGeneration import PassGeneration
from django.db.models.deletion import CASCADE

class Eclipse(models.Model):
    startTime       = models.DateTimeField()
    stopTime        = models.DateTimeField()
    
    duration        = models.FloatField('Duracion', help_text='[minutos]', default=0.0)
    tleDistance     = models.FloatField("Fraccion de dias de distancia al TLE ", default=0)
    
    obsolete        = models.BooleanField(default=True)
    
    
    satellite       = models.ForeignKey(Satellite, related_name='eclipses', on_delete=CASCADE)
    tle             = models.ForeignKey('GroundSegment.Tle', related_name='eclipses', null=True, on_delete=CASCADE)
    
    
    def getStopTimeStr(self):
        return (datetime.strftime(self.stopTime,"%d %b %Y %H:%M:%S"))
        
    def getStartTimeStr(self):
        return (datetime.strftime(self.startTime,"%d %b %Y %H:%M:%S"))
    
    def __eq__(self, other):
        """
        ! NO SE USA ! SE FILTRA DIRECTAMENTE
        Cuando un eclipse es igual al otro?
        1.Cuando comparten nodo o en nuestro caso "satelite"
        2.Cuando sus tiempos de inicio y fin difieren en solo algunos 
        minutos. ¿Cuanto es algunos minutos? 
        """
        
        
        return  (other!=None) and \
                (self.satellite==other.satellite) and \
                (other.startTime-timedelta(minutes=5) <= self.startTime    <=  other.startTime+timedelta(minutes=5)) and \
                (other.stopTime-timedelta(minutes=5)  <= self.stopTime <=  other.stopTime+timedelta(minutes=5))    
    
    def getDuration(self):
        return (self.stopTime-self.startTime).total_seconds()
    
    def getDurationStr(self):
        """
        pasar la duracion de la pasada a un string que indique min:sec
        """
        intervalo=(self.stopTime-self.startTime).total_seconds()
        minutos = int(intervalo//60)
        segundos= int((intervalo % 60))

        return '%s:%s' % (str(minutos).zfill(2),str(segundos).zfill(2))#(self.stopTime-self.startTime)
    
    
    
    def save(self, *args, **kwargs):
        self.duration = self.getDuration()
        self.tleDistance = (self.startTime-self.tle.epoch).total_seconds()/86400
        
        super(Eclipse, self).save(*args, **kwargs)

    def __str__(self):
        return self.satellite.code+", "+str(self.startTime)+"-"+str(self.stopTime)

    
           

    

GroundSegment/GroundSegment/models/Pasada.py
'''
Created on Sep 2, 2016

@author: ubuntumate
'''
from datetime import datetime, timedelta
from django.db import models
from GroundSegment.models.Satellite import Satellite
from GroundSegment.models.Tle import Tle
from GroundSegment.models.Sitio import Sitio
from GroundSegment.models.PassGeneration import PassGeneration
from django.db.models.deletion import CASCADE

class Pasada(models.Model):
    """
    TODO: Mucha informacion redundante
    """
    
    satellite       = models.ForeignKey(Satellite, related_name='pasadas', on_delete=CASCADE)
    tle             = models.ForeignKey(Tle, related_name='pasadas', null=True, on_delete=CASCADE)
    sitio           = models.ForeignKey(Sitio,related_name='pasadas', on_delete=CASCADE)
    startTime       = models.DateTimeField()
    stopTime        = models.DateTimeField()
    duration        = models.FloatField('Duracion', help_text='[minutos]', default=0.0)
    passGeneration  = models.ForeignKey(PassGeneration, on_delete=CASCADE, related_name="passes")
    
    def getStopTimeStr(self):
        return (datetime.strftime(self.stopTime,"%d %b %Y %H:%M:%S"))
        
    def getStartTimeStr(self):
        return (datetime.strftime(self.startTime,"%d %b %Y %H:%M:%S"))

    def getDuration(self):
        return (self.stopTime-self.startTime).total_seconds()
    
    def getDurationStr(self):
        """
        pasar la duracion de la pasada a un string que indique min:sec
        """
        intervalo=(self.stopTime-self.startTime).total_seconds()
        minutos = int(intervalo//60)
        segundos= int((intervalo % 60))

        return '%s:%s' % (str(minutos).zfill(2),str(segundos).zfill(2))#(self.stopTime-self.startTime)
        
    
    def save(self, *args, **kwargs):
        self.duration = self.getDuration()
        super(Pasada, self).save(*args, **kwargs)

    def __str__(self):
        return self.satellite.code+", "+self.sitio.name+", "+str(self.startTime)+"-"+str(self.stopTime)
    
    
    
    

GroundSegment/GroundSegment/models/Propagation.py
'''
Created on Aug 29, 2016

@author: ubuntumate
'''

from django.db import models

from GroundSegment.models.Tle import Tle
from GroundSegment.models.Satellite import Satellite
from django.db.models.deletion import PROTECT

class Propagation(models.Model):
    created     = models.DateTimeField(auto_now_add=True)
    tle         = models.ForeignKey(Tle, related_name='propagations', on_delete=PROTECT)

    satellite   = models.ForeignKey(Satellite, related_name='propagations', on_delete=PROTECT)
    final       = models.BooleanField(default = False)

GroundSegment/GroundSegment/models/Site.py
'''
Created on Sep 16, 2016

@author: ubuntumate
'''

from django.db import models
from GroundSegment.models.Satellite import Satellite
from _datetime import datetime, timedelta
from django.utils.timezone import utc
from GroundSegment.Utils.UtilsFunctions import *
#from GroundSegment.models.Satellite import Satellite
#from django.contrib.admin.utils import help_text_for_field
"""

class Site(models.Model):
    name        = models.CharField("Nombre del Sitio", max_length=100, unique=True)
    latitude    = models.FloatField('latitude', help_text='[Grados Decimales]')
    longitude   = models.FloatField('Longitud', help_text='[Grados Decimales]')
    altitude    = models.FloatField('altura', help_text='[metros]')
    
    def setLatitude(self, value):
        #Meter proteccion
        self.latitude = value
        
    def setLongitude(self, value):
        #Meter proteccion
        self.longitude = value
    
    def setAltitude(self, value):
        #Meter proteccion
        self.altitude = value

    def getPass(self, fro, to, satellite):
        #hacer todos los calculos
        import ephem;
        
        #from calendar import timegm
        
        #Remplazar site por el sitio, entidad no creada aun
        
        tle = satellite.getLastTLE()
        
        sat = ephem.readtle(satellite.code, tle.getLine1(), tle.getLine2())
        
        #iss = ephem.readtle(line1, line2, line3)
        #iss.compute('2003/3/23')
        
        ifro = ephem.Date(fro)
        ito = ephem.Date(to)
        
        site = ephem.Observer()
        site.lon = str( self.longitude )
        site.lat = str( self.latitude )
        site.elevation = self.altitude
        site.name = self.name
        site.date = ifro
        site.epoch = ifro
        
        #while ifro < ito:   
        while site.date < ito:
            sat.compute(site)
            tr, azr, tt, altt, ts, azs = site.next_pass(sat)
            
            duration    = int((ts - tr) *60*60*24)
            rise_time   = datetime_from_time(tr)
            max_time    = datetime_from_time(tt)
            set_time    = datetime_from_time(ts)
            
            site.date = rise_time + timedelta(seconds=duration)
            print('Date:', site.date, "rise_time ", rise_time, "set_time ", set_time)   
                
            
        
        return None

        #site.date = 
        #site.next_transit(esat)
        #site.next_rising(esat)
        
        #Faltaria filtrar por fechas!!, investigar como hacer y pelearla, con un ejemplo nos alcanza para todo
        #el proyecto
        #pd = PropagationDetail.objects.filter(propagation__satellite=Satellite, )
        
        #if pd.count()!=(fro-to).total_seconds():
            #El detalle de propagacion no coincide con el total buscado, por tanto se requiere propagar los faltantes
        
        #Se imprime los detalles de propagacion del satellite solo como muestra, quitar el print
        
        #for pr in pd:
        #    print(pr.positionX, pr.positionY, pr.positionZ)
        
      
"""        
       
       

GroundSegment/GroundSegment/templates/SingleTlmyVarPlotView.html
{% extends "main.html" %} 
{% block content %}
{% load static %}
<h1>Telemetry var  (Satellite: {{satellite.code}} ) </h1>


<form method='GET' action=''>
	<div class="breadcrumbs">
	    Telemetry var: 
	    <select id="tbtelemetryvar" name='tbtelemetryvar'>
			{% for tvt in telemetryVarTypes %}
		   		<option value="{{tvt.pk}}"
		       		{% if tvt.pk == current_tvt_id %}selected="selected"{% endif %}>
		       		{{tvt.code|capfirst}}
		   		</option>
		  	{% endfor %}
		</select>
	    
	    From: <input type="datetime-local" value='{{request.GET.tbdesde}}' name='tbdesde'/>
	    To: <input type="datetime-local" value='{{request.GET.tbhasta}}' name='tbhasta'/>
	    <input type="submit" name="submit" value="Process"/>	    
	   <!--  <h1> <input type="submit" name="descargar" value="Descargar"/> </h1> --> 
    </div>              
    
</form>
<!--  <h1> Satellite: {{tbsatellite}} </h1> --> 
<div class="table-responsive">
 <img src="data:image/png;base64,{{plot|safe}}" width="60%">
</div>
{% endblock %}

GroundSegment/GroundSegment/templates/about.html
{% extends "base.html" %} 
{% block content %}
{% load staticfiles %}


<h1><strong>MDIAE-Segmento Terreno</strong></h1>
<div>
<table>
	<tbody>
		<tr>
		
			<!--  <th><img src="{% static "/GroundSegment/Soligo.jpg" %}" alt="Soligo" height="64" width="64"/></th> -->
			<th><img src="{% static "Soligo.jpg" %}" alt="Soligo" height="64" width="64"/></th>
			
			<th>Pablo Soligo</th>
			<th>Ingeniero de sistema</th>
		</tr>
		<tr>
			<th><img src="{% static "Zapata.jpg" %}" alt="Zapata" height="64" width="64"/></th>
			<th>Elbio Zapata</th>
			<th>Control Unit</th>
		</tr>
		<tr>
			<th><img src="{% static "Valenti.jpg" %}" alt="Valenti" height="64" width="64"/></th>
			<th>Maria Cecilia Valenti</th>
			<th>Orbits Dynamics</th>
		</tr>
		<tr>
			<th><img src="{% static "Barbieri.jpg" %}" alt="Barbieri" height="64" width="64"/></th>
			<th>Ricardo Barbieri</th>
			<th>Mission Unit</th>
		</tr>
		<tr>
			<th><img src="{% static "Robin.jpg" %}" alt="Robin" height="64" width="64"/></th>
			<th>Jose Robin</th>
			<th>Ground Station</th>
		</tr>
		<tr>
			<th><img src="{% static "montilla.jpg" %}" alt="Robin" height="64" width="64"/></th>
			<th>Alfonso Montilla</th>
			<th>Colaboración especial y revisión</th>
		</tr>
		
	</tbody>
</table>
</div>

{% endblock %}

GroundSegment/GroundSegment/templates/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!-- bloque de contenido para el título-->
    <title>{% block title %}GS-MDIAE{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
</head>
<body>
    <div id="header">
        <!-- bloque de contenido para el menú-->
        {% block header %}
           {% include 'nav.html' %}
        {% endblock %}
    </div>
    <div class="container">
        <!-- bloque de contenido para el contenido de la página-->
      <div class="row-fluid">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    
    <footer class="footer">
        <!-- bloque de contenido para el footer-->
        {% block footer %}{% endblock %}
    </footer>
</body>
</html>

GroundSegment/GroundSegment/templates/eclipses.html
{% extends "base.html" %} 
{% block content %}
{% load static %}
<h1>Eclipses  (Satellite: {{satellite.code}} ) </h1>


<form method='GET' action=''>
	<div class="breadcrumbs">
	    Satellite: 
	    <select id="tbsatellite" name='tbsatellite'>
			{% for s in sat_list %}
		   		<option value="{{s.pk}}"
		       		{% if s.pk == current_sat_id %}selected="selected"{% endif %}>
		       		{{s.code|capfirst}}
		   		</option>
		  	{% endfor %}
		</select>
	
	    From: <input type="date" value='{{request.GET.tbdesde}}' name='tbdesde'/>
	    To: <input type="date" value='{{request.GET.tbhasta}}' name='tbhasta'/>
	    <input type="submit" name="submit" value="Process"/>	    
	   <!--  <h1> <input type="submit" name="descargar" value="Descargar"/> </h1> --> 
    </div>              
    
</form>
<!--  <h1> Satellite: {{tbsatellite}} </h1> --> 
<div class="table-responsive">
 <table class="table table-striped table-bordered table-condensed" width="100%">
  <tr>
  	<th>Eclipse id</th>
    <th>Start Time [UTC]</th>
    <th>Stop Time [UTC]</th> 
    <th>Duration [min]</th> 
   </tr>
 
  {% for p in eclipse_list %}
  <tr>
  	<td>{{p.pk}}</td>
    <td>{{p.getStartTimeStr}}</td>
    <td>{{p.getStopTimeStr}}</td> 
    <td>{{p.getDurationStr}}</td> 
   </tr>
  {% endfor %}
</table>


{% endblock %}

 <!-- {% if messages %}
	<ul>
	   {% for message in messages %}
		   <li>{{ message }}</li>
	   {% endfor %}
	</ul>
  {% endif %}  -->  

GroundSegment/GroundSegment/templates/home.html
{% extends 'base2.html' %}
 
{% block content %}

        <table>
            <tr>
                <td>{{ user.username.label_tag }}</td>
                <td>{{ user.username }}</td>
            </tr>
     
            <tr>
                <td>{{ user.email.label_tag }}</td>
                <td>{{ user.email }}</td>
            </tr>
     
            <tr>
                <td>{{ user.first_name.label_tag }}</td>
                <td>{{ user.first_name }}</td>
            </tr>
     
            <tr>
                <td>{{ user.last_name.label_tag }}</td>
                <td>{{ user.last_name }}</td>
            </tr>
     
            <tr>
                <td>{{ user.date_joined.label_tag }}</td>
                <td>{{ user.date_joined }}</td>
            </tr>
     
            <tr>
                <td>{{ user.last_login.label_tag }}</td>
                <td>{{ user.last_login }}</td>
            </tr>

            <tr>
                <td>PERMISOS</td>
                <td>{{ perms.foo }}</td>
            </tr>
     
        </table>

        {% if perms.TlmyVarType %}
             <p>Usted tiene permiso para editar {{perms.add_tlmyvartype}}</p>
        {% else %}
             <h2>Usted  no tiene permiso</h2>
        {% endif %}

 
{% endblock %}

GroundSegment/GroundSegment/templates/login.html
{% extends "base.html" %}
 
{% block content %}
    {% if form.errors %}
        <p>Ingrese Usuario y Password!!!</p>
    {% endif %}
 
    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>
 
        <input type="submit" value="login"/> <input type="hidden" name="next"
                                                    value="{{ next }}"/>
    </form>
 
{% endblock %}

GroundSegment/GroundSegment/templates/pasadas.html
{% extends "base.html" %} 
{% block content %}
{% load static %}
<h1>Pasadas  (Satellite: {{satellite.code}}  , Sitio: {{sitio.name}} ) </h1>

<form method='GET' action=''> 
	<div class="breadcrumbs">
	    Satellite: 
	    <select id="tbsatellite" name='tbsatellite'>
			{% for s in sat_list %}
		   		<option value="{{s.pk}}"
		       		{% if s.pk == current_sat_id %}selected="selected"{% endif %}>
		       		{{s.code|capfirst}}
		   		</option>
		  	{% endfor %}
		</select>
	
	    Site: 
	    <select name="tbsitio">
	    	{% for s in site_list %}
	    		<option value="{{s.pk}}"
		       		{% if s.pk == current_site_id %}selected="selected"{% endif %}>
		       		{{s.name|capfirst}}
		   		</option>
			{% endfor %}
	    </select>
	    From: <input type="date" value='{{request.GET.tbdesde}}' name='tbdesde'/>
	    To: <input type="date" value='{{request.GET.tbhasta}}' name='tbhasta'/>
		<input type="submit" value="Process" name="action" />
    </div>
    
</form>
<!--  <h1> Satellite: {{tbsatellite}}  , Sitio: {{tbsitio}} </h1> --> 
<div class="table-responsive">
 <table class="table table-striped table-bordered table-condensed" width="100%">
  <tr>
  	<th>Pass id</th>
    <th>Start Time [UTC]</th>
    <th>Stop Time [UTC]</th> 
    <th>Duration [min]</th>
   <!-- <th>TLE</th> --> 
   </tr>
  {% for p in pasada_list %}
  <tr>
  	<td>{{p.pk}}</td>
    <td>{{p.getStartTimeStr}}</td>
    <td>{{p.getStopTimeStr}}</td> 
    <td>{{p.getDurationStr}}</td>
   <!--	<td>Descargar TLE</td> --> 
   </tr>
  {% endfor %}
</table>


{% endblock %}